// Mocks generated by Mockito 5.4.6 from annotations
// in pass_gen/test/unit/usecases/storage/get_passwords_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pass_gen/core/errors/failures.dart' as _i5;
import 'package:pass_gen/domain/entities/password_entry.dart' as _i6;
import 'package:pass_gen/domain/repositories/storage_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [StorageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageRepository extends _i1.Mock implements _i3.StorageRepository {
  MockStorageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.StorageFailure, bool>> savePasswords(
    List<_i6.PasswordEntry>? passwords,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#savePasswords, [passwords]),
            returnValue: _i4.Future<_i2.Either<_i5.StorageFailure, bool>>.value(
              _FakeEither_0<_i5.StorageFailure, bool>(
                this,
                Invocation.method(#savePasswords, [passwords]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.StorageFailure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.StorageFailure, List<_i6.PasswordEntry>>>
  getPasswords() =>
      (super.noSuchMethod(
            Invocation.method(#getPasswords, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.StorageFailure, List<_i6.PasswordEntry>>
                >.value(
                  _FakeEither_0<_i5.StorageFailure, List<_i6.PasswordEntry>>(
                    this,
                    Invocation.method(#getPasswords, []),
                  ),
                ),
          )
          as _i4.Future<
            _i2.Either<_i5.StorageFailure, List<_i6.PasswordEntry>>
          >);

  @override
  _i4.Future<_i2.Either<_i5.StorageFailure, bool>> removePasswordAt(
    int? index,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removePasswordAt, [index]),
            returnValue: _i4.Future<_i2.Either<_i5.StorageFailure, bool>>.value(
              _FakeEither_0<_i5.StorageFailure, bool>(
                this,
                Invocation.method(#removePasswordAt, [index]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.StorageFailure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.StorageFailure, bool>> clearStorage() =>
      (super.noSuchMethod(
            Invocation.method(#clearStorage, []),
            returnValue: _i4.Future<_i2.Either<_i5.StorageFailure, bool>>.value(
              _FakeEither_0<_i5.StorageFailure, bool>(
                this,
                Invocation.method(#clearStorage, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.StorageFailure, bool>>);
}
