// Mocks generated by Mockito 5.4.6 from annotations
// in pass_gen/test/unit/usecases/category/create_category_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pass_gen/domain/entities/category.dart' as _i2;
import 'package:pass_gen/domain/repositories/category_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCategory_0 extends _i1.SmartFake implements _i2.Category {
  _FakeCategory_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryRepository extends _i1.Mock
    implements _i3.CategoryRepository {
  MockCategoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Category>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i4.Future<List<_i2.Category>>.value(<_i2.Category>[]),
          )
          as _i4.Future<List<_i2.Category>>);

  @override
  _i4.Future<_i2.Category?> getById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i4.Future<_i2.Category?>.value(),
          )
          as _i4.Future<_i2.Category?>);

  @override
  _i4.Future<_i2.Category> create(_i2.Category? category) =>
      (super.noSuchMethod(
            Invocation.method(#create, [category]),
            returnValue: _i4.Future<_i2.Category>.value(
              _FakeCategory_0(this, Invocation.method(#create, [category])),
            ),
          )
          as _i4.Future<_i2.Category>);

  @override
  _i4.Future<_i2.Category> update(_i2.Category? category) =>
      (super.noSuchMethod(
            Invocation.method(#update, [category]),
            returnValue: _i4.Future<_i2.Category>.value(
              _FakeCategory_0(this, Invocation.method(#update, [category])),
            ),
          )
          as _i4.Future<_i2.Category>);

  @override
  _i4.Future<void> delete(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Category>> getSystemCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getSystemCategories, []),
            returnValue: _i4.Future<List<_i2.Category>>.value(<_i2.Category>[]),
          )
          as _i4.Future<List<_i2.Category>>);

  @override
  _i4.Future<List<_i2.Category>> getUserCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getUserCategories, []),
            returnValue: _i4.Future<List<_i2.Category>>.value(<_i2.Category>[]),
          )
          as _i4.Future<List<_i2.Category>>);
}
