// Mocks generated by Mockito 5.4.6 from annotations
// in pass_gen/test/usecases/auth/get_auth_state_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pass_gen/core/errors/failures.dart' as _i6;
import 'package:pass_gen/domain/entities/auth_result.dart' as _i7;
import 'package:pass_gen/domain/entities/auth_state.dart' as _i3;
import 'package:pass_gen/domain/repositories/auth_repository.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthState_1 extends _i1.SmartFake implements _i3.AuthState {
  _FakeAuthState_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i4.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> isPinSetup() =>
      (super.noSuchMethod(
            Invocation.method(#isPinSetup, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<_i2.Either<_i6.AuthFailure, bool>> setupPin(String? pin) =>
      (super.noSuchMethod(
            Invocation.method(#setupPin, [pin]),
            returnValue: _i5.Future<_i2.Either<_i6.AuthFailure, bool>>.value(
              _FakeEither_0<_i6.AuthFailure, bool>(
                this,
                Invocation.method(#setupPin, [pin]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.AuthFailure, bool>>);

  @override
  _i5.Future<_i2.Either<_i6.AuthFailure, _i7.AuthResult>> verifyPin(
    String? pin,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPin, [pin]),
            returnValue:
                _i5.Future<_i2.Either<_i6.AuthFailure, _i7.AuthResult>>.value(
                  _FakeEither_0<_i6.AuthFailure, _i7.AuthResult>(
                    this,
                    Invocation.method(#verifyPin, [pin]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.AuthFailure, _i7.AuthResult>>);

  @override
  _i5.Future<_i2.Either<_i6.AuthFailure, bool>> changePin(
    String? oldPin,
    String? newPin,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePin, [oldPin, newPin]),
            returnValue: _i5.Future<_i2.Either<_i6.AuthFailure, bool>>.value(
              _FakeEither_0<_i6.AuthFailure, bool>(
                this,
                Invocation.method(#changePin, [oldPin, newPin]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.AuthFailure, bool>>);

  @override
  _i5.Future<_i2.Either<_i6.AuthFailure, bool>> removePin(String? pin) =>
      (super.noSuchMethod(
            Invocation.method(#removePin, [pin]),
            returnValue: _i5.Future<_i2.Either<_i6.AuthFailure, bool>>.value(
              _FakeEither_0<_i6.AuthFailure, bool>(
                this,
                Invocation.method(#removePin, [pin]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.AuthFailure, bool>>);

  @override
  _i5.Future<_i3.AuthState> getAuthState() =>
      (super.noSuchMethod(
            Invocation.method(#getAuthState, []),
            returnValue: _i5.Future<_i3.AuthState>.value(
              _FakeAuthState_1(this, Invocation.method(#getAuthState, [])),
            ),
          )
          as _i5.Future<_i3.AuthState>);

  @override
  void resetAuthState() => super.noSuchMethod(
    Invocation.method(#resetAuthState, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<bool> checkLockoutExpired() =>
      (super.noSuchMethod(
            Invocation.method(#checkLockoutExpired, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}
