// Mocks generated by Mockito 5.4.6 from annotations
// in pass_gen/test/unit/usecases/log/get_logs_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pass_gen/domain/entities/security_log.dart' as _i4;
import 'package:pass_gen/domain/repositories/security_log_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SecurityLogRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecurityLogRepository extends _i1.Mock
    implements _i2.SecurityLogRepository {
  MockSecurityLogRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> logEvent(
    String? actionType, {
    Map<String, dynamic>? details,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logEvent, [actionType], {#details: details}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.SecurityLog>> getLogs({int? limit = 1000}) =>
      (super.noSuchMethod(
            Invocation.method(#getLogs, [], {#limit: limit}),
            returnValue: _i3.Future<List<_i4.SecurityLog>>.value(
              <_i4.SecurityLog>[],
            ),
          )
          as _i3.Future<List<_i4.SecurityLog>>);

  @override
  _i3.Future<List<_i4.SecurityLog>> getLogsByType(
    String? actionType, {
    int? limit = 100,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getLogsByType, [actionType], {#limit: limit}),
            returnValue: _i3.Future<List<_i4.SecurityLog>>.value(
              <_i4.SecurityLog>[],
            ),
          )
          as _i3.Future<List<_i4.SecurityLog>>);

  @override
  _i3.Future<void> clearOldLogs({int? keepLast = 1000}) =>
      (super.noSuchMethod(
            Invocation.method(#clearOldLogs, [], {#keepLast: keepLast}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int> count() =>
      (super.noSuchMethod(
            Invocation.method(#count, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
