// Mocks generated by Mockito 5.4.6 from annotations
// in pass_gen/test/usecases/password/save_password_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pass_gen/core/errors/failures.dart' as _i5;
import 'package:pass_gen/domain/entities/password_config.dart' as _i8;
import 'package:pass_gen/domain/entities/password_generation_settings.dart'
    as _i7;
import 'package:pass_gen/domain/entities/password_result.dart' as _i6;
import 'package:pass_gen/domain/repositories/password_generator_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PasswordGeneratorRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPasswordGeneratorRepository extends _i1.Mock
    implements _i3.PasswordGeneratorRepository {
  MockPasswordGeneratorRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.PasswordGenerationFailure, _i6.PasswordResult>>
  generatePassword(_i7.PasswordGenerationSettings? settings) =>
      (super.noSuchMethod(
            Invocation.method(#generatePassword, [settings]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.PasswordGenerationFailure, _i6.PasswordResult>
                >.value(
                  _FakeEither_0<
                    _i5.PasswordGenerationFailure,
                    _i6.PasswordResult
                  >(this, Invocation.method(#generatePassword, [settings])),
                ),
          )
          as _i4.Future<
            _i2.Either<_i5.PasswordGenerationFailure, _i6.PasswordResult>
          >);

  @override
  _i4.Future<_i2.Either<_i5.PasswordGenerationFailure, _i6.PasswordResult>>
  restorePassword(String? config) =>
      (super.noSuchMethod(
            Invocation.method(#restorePassword, [config]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.PasswordGenerationFailure, _i6.PasswordResult>
                >.value(
                  _FakeEither_0<
                    _i5.PasswordGenerationFailure,
                    _i6.PasswordResult
                  >(this, Invocation.method(#restorePassword, [config])),
                ),
          )
          as _i4.Future<
            _i2.Either<_i5.PasswordGenerationFailure, _i6.PasswordResult>
          >);

  @override
  _i4.Future<_i2.Either<_i5.PasswordGenerationFailure, _i8.PasswordConfig>>
  createPasswordConfig({
    required String? service,
    required String? masterPassword,
    required _i7.PasswordGenerationSettings? settings,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPasswordConfig, [], {
              #service: service,
              #masterPassword: masterPassword,
              #settings: settings,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.PasswordGenerationFailure, _i8.PasswordConfig>
                >.value(
                  _FakeEither_0<
                    _i5.PasswordGenerationFailure,
                    _i8.PasswordConfig
                  >(
                    this,
                    Invocation.method(#createPasswordConfig, [], {
                      #service: service,
                      #masterPassword: masterPassword,
                      #settings: settings,
                    }),
                  ),
                ),
          )
          as _i4.Future<
            _i2.Either<_i5.PasswordGenerationFailure, _i8.PasswordConfig>
          >);

  @override
  _i4.Future<_i2.Either<_i5.PasswordGenerationFailure, String>> decryptPassword(
    _i8.PasswordConfig? config,
    String? masterPassword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#decryptPassword, [config, masterPassword]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.PasswordGenerationFailure, String>
                >.value(
                  _FakeEither_0<_i5.PasswordGenerationFailure, String>(
                    this,
                    Invocation.method(#decryptPassword, [
                      config,
                      masterPassword,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.PasswordGenerationFailure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.PasswordGenerationFailure, Map<String, dynamic>>>
  savePassword({
    required String? service,
    required String? password,
    required String? config,
    int? categoryId,
    String? login,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#savePassword, [], {
              #service: service,
              #password: password,
              #config: config,
              #categoryId: categoryId,
              #login: login,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<
                    _i5.PasswordGenerationFailure,
                    Map<String, dynamic>
                  >
                >.value(
                  _FakeEither_0<
                    _i5.PasswordGenerationFailure,
                    Map<String, dynamic>
                  >(
                    this,
                    Invocation.method(#savePassword, [], {
                      #service: service,
                      #password: password,
                      #config: config,
                      #categoryId: categoryId,
                      #login: login,
                    }),
                  ),
                ),
          )
          as _i4.Future<
            _i2.Either<_i5.PasswordGenerationFailure, Map<String, dynamic>>
          >);
}
